# Generated by Django 5.2.5 on 2025-09-08 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_transaction_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('cash', 'Cash'), ('saving', 'Saving'), ('investing_retirement', 'Investing & Retirement')], max_length=24)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default='Account', max_length=30),
        ),
        migrations.AlterField(
            model_name='account',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='api.institution'),
        ),
    ]
