# Generated by Django 5.2.8 on 2025-11-12 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_chatkitthread'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatKitUserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chatkit_session', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chatkit_user_sessions',
                'indexes': [models.Index(fields=['user'], name='chatkit_use_user_id_35d468_idx')],
            },
        ),
    ]
