# Generated by Django 5.2.1 on 2025-05-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.TextField(default='placeholder@example.com', max_length=40, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.TextField(default='John', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.TextField(default='Doe', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.TextField(default='job', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='password', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(max_length=100, unique=True),
        ),
    ]
