# Generated by Django 5.2.8 on 2025-11-12 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_institution_account_name_alter_account_institution'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatKitThread',
            fields=[
                ('thread_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatkit_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chatkit_threads',
                'indexes': [models.Index(fields=['thread_id'], name='chatkit_thr_thread__dc91cf_idx'), models.Index(fields=['user'], name='chatkit_thr_user_id_31c7fb_idx')],
            },
        ),
    ]
