# Generated by Django 5.2.1 on 2025-05-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_email_user_first_name_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='occupation',
            field=models.TextField(blank=True, default='job', max_length=30, null=True),
        ),
    ]
