# Generated by Django 5.2.1 on 2025-05-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='occupation',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
