# Generated by Django 5.2.1 on 2025-05-27 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='income',
            table='income',
        ),
    ]
